Repository masterchef2209/GETSETFOSSDebuggingTasks, pull requests merged in 2019-11, with the labels that each got.

#14 screenshots of soln of err3
  Screenshot from 2019-11-04 16-49-29.png
  Screenshot from 2019-11-04 16-49-35.png
  Screenshot from 2019-11-04 16-49-42.png
  debugging/err3_cf1206C.txt
Labels: Easy, getsetfoss2019

#16 Update err_cf1066E.txt
  debugging/err_cf1066E.txt
Labels: Medium, getsetfoss2019

#18 Yk1ax patch 1
  Screenshot for task4.png
  debugging/err4_cf1245D.txt
Labels: Medium, getsetfoss2019

#22 Issue #19 Debug err5_cf778A.txt(intended number of changes in code is <=2)
  Screenshot of Submission of String Game.png
  debugging/err5_cf778A.txt
Labels: Hard, getsetfoss2019

#23 Issue #21 Debug err6_687C.txt (intended number of changes in code is <=3)
  Submission of The Values You Can Make.png
  debugging/err6_687C.txt
Labels: Pro, getsetfoss2019
